package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class Student_Fees extends javax.swing.JFrame {

    /**
     * Creates new form Student_Fees
     */
    public Student_Fees() {
        initComponents();
    }
    public int amount=0;
    public int count=0;
    
    
             
             
         
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        feesamount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fst = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Fees(School management System)");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Student Fees");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Student ID:-");

        feesamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesamountActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Fetch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fst.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {{null, null, null, null, null}},new String [] {"St_ID", "Jan-March", "April-Jun", "Jul-Sep", "Oct-Dec"}) 
            {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fst);
        if (fst.getColumnModel().getColumnCount() > 0) {
            fst.getColumnModel().getColumn(0).setResizable(false);
            fst.getColumnModel().getColumn(1).setResizable(false);
            fst.getColumnModel().getColumn(2).setResizable(false);
            fst.getColumnModel().getColumn(3).setResizable(false);
            fst.getColumnModel().getColumn(4).setResizable(false);
        }

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Jan-Mar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Apr-Jun");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Jul-Sep");

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("Oct-Dec");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Fees Amount:-");

        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Fetch");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(feesamount, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feesamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void feesamountActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Connection connect = null;
        
        ResultSet rs;
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql="select * from fees where Student_ID=?;";
             PreparedStatement pstmt=connect.prepareStatement(sql);
             pstmt.setString(1,sid.getText());
             rs=pstmt.executeQuery();
             
             fst.setModel(DbUtils.resultSetToTableModel(rs));
             
             
             
            }
        catch(SQLException ex)
            {
             JOptionPane.showMessageDialog(Student_Fees.this,"Particular Student Id does not exist");
            
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
        
        
        
        
        
        
        
    }                                        

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        
        
        
    }                                          

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
       Connection connect = null;
        
        ResultSet rs;
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql="SELECT amount FROM fees_amount where class in (SELECT class from student where student_ID = ?);";
             PreparedStatement pstmt=connect.prepareStatement(sql);
             pstmt.setString(1,sid.getText());
             rs=pstmt.executeQuery();
             if(rs.next()){
                amount=rs.getInt(1);
             }
/////////////////////////////////////////////////////////////////////////////////////////////////////            
          if(jCheckBox1.isSelected()){
              count+=1;
               Connection connect1 = null;
        
       
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect1=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql2="UPDATE fees SET `Jan-March` = 'paid' WHERE St_ID = ?;";
             PreparedStatement pstmt1=connect1.prepareStatement(sql2);
             pstmt1.setString(1,sid.getText());
             pstmt1.executeUpdate(); 
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
              
              
              
          }
          
//////////////////////////////////////////////////////////////////////////////////////////////
          if(jCheckBox2.isSelected()){
              count+=1;
               Connection connect2 = null;
        
        ResultSet rs3;
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect2=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql3="UPDATE FEES SET `April-Jun` = 'paid' WHERE St_ID = ?;";
             
             PreparedStatement pstmt2=connect2.prepareStatement(sql3);
             pstmt2.setString(1,sid.getText());
             
             
             pstmt2.executeUpdate();
         
             
             
             
             
             
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
              
              
          }
//////////////////////////////////////////////////////////////////////////////////////////////////////////
          if(jCheckBox3.isSelected()){
              count+=1;
               Connection connect3 = null;
        
        ResultSet rs4;
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect3=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql4="UPDATE FEES SET `Jul-Sep` = 'paid' WHERE St_ID = ?";
             
             PreparedStatement pstmt3=connect3.prepareStatement(sql4);
             
             pstmt3.setString(1,sid.getText());
             
            pstmt3.executeUpdate();
             
             
             
             
             
             
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
          }
          
          
///////////////////////////////////////////////////////////////////////////////////////////////////////////
          if(jCheckBox4.isSelected()){
              count+=1;
               Connection connect4 = null;
        
        ResultSet rs5;
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect4=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             String sql5="UPDATE FEES SET `Oct-Dec` = 'paid' WHERE St_ID = ?;";
             
             PreparedStatement pstmt4=connect4.prepareStatement(sql5);
             pstmt4.setString(1,sid.getText());
             
                          
             pstmt4.executeUpdate();
             
             
             
             
             
             
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
   }
//////////////////////////////////////////////////////////////////////////////////////////////              
            amount=amount*count;    
             
             
             
             
             String gunai=String.valueOf(amount);
            feesamount.setText(gunai);
            amount=0;
            count=0;
             
             
             
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
        
        
        
        
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         Connection connect = null;
        
        
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/new_schema","root","anuj3107");
             
             String sql18="INSERT INTO account VALUES (?,?);";
             
             PreparedStatement pstmt2=connect.prepareStatement(sql18);
             pstmt2.setString(1,feesamount.getText());
             pstmt2.setString(2,"sf");
             pstmt2.executeUpdate();
             feesamount.setText("");
             JOptionPane.showMessageDialog(Student_Fees.this,"Fees Paid");
             
             
             
             
             
            }
        catch(SQLException ex)
            {
            System.out.println("error: "+ex);
            }
        catch (ClassNotFoundException e1){
            e1.printStackTrace();
        }
        
        
        
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField feesamount;
    private javax.swing.JTable fst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sid;
    // End of variables declaration                   
}